image: node:10
 
cache:
  paths:
    - node_modules/
 
before_script:
  - apt-get update -qq && apt-get install -y -qq sshpass rsync
 
deploy_stage:
  only:
    refs:
      - /^release.*$/
  stage: deploy
  environment: Stage
  script:
    - yarn install
    - yarn build
    - cd build/
    - ls
    - sshpass -V
    - export SSHPASS=$USER_PASS
    - sshpass -e rsync -r --omit-dir-times -e "ssh -o StrictHostKeyChecking=no -p 60022" . $USER_NAME@$SERVER_IP:/var/www/html/labor
    