image: node:10

cache:
  paths:
    - node_modules/
    - build/

before_script:
  - apt-get update -qq && apt-get install -y -qq sshpass rsync

deploy-dev:
  only:
    - dev
    
  stage: deploy
  script:
    - yarn install
    - yarn build:dev
    - export SSHPASS=$USER_PASS_DEV
    - sshpass -e rsync -r --omit-dir-times -e "ssh -o StrictHostKeyChecking=no -p 22197" build/ $USER_NAME_DEV@$SERVER_IP_DEV:/home/dev/biocoin/admin/build/

deploy-qa:
  only:
    - qa
    
  stage: deploy
  script:
    - yarn install
    - yarn build:qa
    - export SSHPASS=$USER_PASS_QA
    - sshpass -e rsync -r --omit-dir-times -e "ssh -o StrictHostKeyChecking=no -p 22197" build/ $USER_NAME_QA@$SERVER_IP_QA:/home/dev/qa/admin/build/